### ISSUE TITLE
Update sudoers file and grant specific root user privileges to certain users

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/XNAT#17]
For importing data, data processing in the iFIND project, etc., users currently do not use their own account but instead use the `hnadmin` profile because it seems that is the only account that can access super-user privileges, i.e. is included in the [sudoers](https://help.ubuntu.com/community/Sudoers) file. 

This means that if users need to run certain commands as the `root` user, we are less able to accurately monitor and audit user actions, resource usage, etc.

I suggest we:
- Update the sudoers file so that certain users who require super-user privileges can do so via their own user profile rather than the `hnadmin` user profile
- Identify which commands can/should be run by certain users, rather than only the `root` user, such as the data processing commands in the iFIND project

**Comment by dangerdika** [comment]
@heyhaleema I think you've solved this problem already by creating dedicated admin user accounts, can this issue be closed?

**Comment by heyhaleema** [comment]
@dangerdika Agreed! Just to recap, we've created: 
- A `sudoadmins` group and added this to the `sudoers` file
- New accounts for @heyhaleema (`admin_haljazzaf`), @dangerdika (`admin_dvilic`), & @laurencejackson (`admin_ljackson`) and added these to the `sudoadmins` group
