### ISSUE TITLE
Upgrade to XNAT v1.8.7 from current v1.8.3

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/XNAT#20]
See release notes [here](https://wiki.xnat.org/documentation/getting-started-with-xnat/what-s-new-in-xnat/xnat-1-8-5-release-notes).

**Comment by heyhaleema** [comment]
Hey @dangerdika, what is the general process for upgrading XNAT from one version to the next? I agree with your point, though, re: waiting to see if any hotfixes are released before moving forward so let's set a tentative install date of Monday, 5th September, 2022.

Also, since we now have the XNAT users email distribution list, it might be worth us reviewing that (e.g. new users) and coming up with a standard update to send out ahead of time.

@hshuaib90, @laurencejackson, and @AnilMistry - FYI.

**Comment by laurencejackson** [comment]
I can't speak much for XNAT, but with MLFLow on the MLOps server, I like to update it regularly, not necessarily every release but whenever a new fix or feature I think looks good is rolled out. Are there any particularly juicy features in this XNAT update?

General bug fixes are always good, I'm not sure how many of the ones they mention in the release notes anyone has come across? the updates to XNAT's DICOM SCP Receiver functionality sounds like a good one. And scheduled events might be handy.

Another good reason to update on the reg is it'll force us to test how resilient our setup is, an update will probably be required eventually and it may be better to identify these sorts of things early - the first time I updated the MLFlow server I had to debug it for almost a week! 

Anyone bit rambly, looking forward to the update, maybe it'll fix the ML plugin issues!

**Comment by dangerdika** [comment]
I propose we upgrade XNAT to the new 1.8.7 version once Spine and iFIND projects are complete and before we start the next set of data ingestions. @heyhaleema @laurencejackson are you happy with that? We're quite a few versions behind now (still on 1.8.3) and I think the next version of OHIF (which should allow RT data visualisation) may not be possible without an update (according to Dan)

**Comment by dangerdika** [comment]
This work has now been completed with upgrade to 1.8.9.1
