### ISSUE TITLE
Create support accounts for users who may need to use sudo access

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/XNAT#35]
We should create separate user accounts and add these to the sudoers file so that we can better track:

- Who needs access to root privileges
- Which user is accessing root privileges, i.e. versus multiple users using the `hnadmin` account

This can be similar to GSTT's support accounts, e.g. `GSTT\Suprt_<username>`, which are used for sysadmin purposes.

**Comment by heyhaleema** [comment]
I've just created the following new users, and added them to the newly-created `sudoadmins` user group:

- `admin_dvilic`
- `admin_haljazzaf`
- `admin_ljackson`

I've also now added this user group to the `sudoers` file to enable any users in this group to run as `root` only, i.e. these users cannot substitute themselves as any other user.

I will send you, @dangerdika and @laurencejackson, the temporary password assigned to your `admin_` accounts shortly. 

Whenever you've logged in/changed your password, please test whether you can run `sudo -i` successfully :)

- [ ] `admin_dvilic` can run as `root` 
- [x] `admin_haljazzaf` can run as `root` 
- [ ] `admin_ljackson` can run as `root`

**Comment by laurencejackson** [comment]
Thanks Haleema, can confirm all working for me.

**Comment by dangerdika** [comment]
Thanks Haleema, works for me too!
