### ISSUE TITLE
Links to anonymisation scripts broken in README

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/XNAT#66]
If you try to open the anonymisation scripts from the links in the README, you get a 404.

https://github.com/GSTT-CSC/XNAT#de-identification-via-qr

Think they should be relinked to here:

https://github.com/GSTT-CSC/XNAT/tree/main/xnat-csc/helpers

**Comment by heyhaleema** [comment]
Note: To be fixed after #67 is merged.
